### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by 0sae** [mt8/base-item-list#13]
プラグインのご提供ありがとうございます。
「よくある質問」も熟読して設定したつもりなのですが、以下のエラーが出てしまい、商品一覧が表示されません。

```
Warning: count(): Parameter must be an array or an object that implements Countable in /home/…省略/wp-content/plugins/base-item-list/class-BaseItemList.php on line 71

Warning: count(): Parameter must be an array or an object that implements Countable in /home/…省略/wp-content/plugins/base-item-list/class-BaseItemList.php on line 72

Warning: array_slice() expects parameter 1 to be array, null given in /home/…省略/wp-content/plugins/base-item-list/class-BaseItemList.php on line 74
```

エラーから調べたところ、
php7.2から、count(null)に対して0ではなく、warningを返すとの記事があったのですが
私はPHPを理解していないので解決ならず、ここで質問させていただくに至りました。

なお、以前ここであった質問の回答で

- BASE APIアプリ作成時に、「検索APIを利用する」にチェックを入れている
- （検索API用）の、client_id・client_secretを設定しているBASE APIアプリ内に検索用ではない、client_id・client_secretも記載されているので注意が必要です

と返答されていましたが、こちらは問題ないようです。

お手間をかけますが、ご返信いただけますと大変助かります。
よろしくお願いいたします。

使用WPバージョン 5.4–ja 
使用PHPバージョン7.2.27

**Comment by mt8** [comment]
この辺に　var_dump($json); とかを入れてデバックしてみてください。
https://github.com/mt8/base-item-list/blob/master/class-BaseItemList.php#L69

たぶんAPIからデータが取れてないのでしょう。
PHP7.2からの問題はそのうち対応すると思います。

**Comment by 0sae** [comment]
お忙しい中無償での対応ありがとうございます。

おっしゃる通りの場所に（全角を半角にした上で）var_dump（$ json）; を組み込み、UPしなおしたのですが、特に変化はありませんでした。

私はPHPは勉強中でして、デバッグの仕方も調べてみたのですが理解できずで…。

>たぶんAPIからデータが取れてないのでしょう。

APIからのデータがとれていないと言う事は、こちらの設定ミスの可能性が高いということでしょうか。

BASEショップ側は基本クローズ状態で、商品も非表示の設定にしておりまして。
プラグインの動作チェック時だけ一時的にオープン・商品公開にして確認しているのですが、もしやタイムラグがあるとかそういったことも考えられるのでしょうか。

以上、お手数をおかけしますが、ご返信いただけると幸いです。よろしくお願いいたします。

**Comment by mt8** [comment]
> APIからのデータがとれていないと言う事は、こちらの設定ミスの可能性が高いということでしょうか。

はい、別のツールなどでAPIキーが有効か試してみて下さい
