### ISSUE TITLE
商品が表示されない

### ISSUE THREAD

**Issue by terutika0604** [mt8/base-item-list#14]
先ほどまで表示されていた商品データが出力されなくなりました。
ul要素までは出力されており、li要素から出力されていません。
エラーメッセージは出ていません。
どうしたらいいでしょうか。

**Comment by mt8** [comment]
APIからデータが取得できていないのかもしれません。

ここを
https://github.com/mt8/base-item-list/blob/master/class-BaseItemList.php#L84

```
echo '<!--';
var_dump( $response );
echo '-->'; 
return null;
```

こんな風に書き換えてHTMLコメントに表示されるエラーを確認してみてください。
コード書き換えに伴うエラー発生については自己責任でお願いしますね。

**Comment by terutika0604** [comment]
ご回答ありがとうございます。
ショップの公開設定を非公開にしたのが問題だったようですm(__)m

**Comment by mt8** [comment]
なるほど
https://docs.thebase.in/docs/api/search/

こちらにも書かれていますね。
※非公開の商品は検索できません。

クローズします。
