### ISSUE TITLE
商品リストの表示順変更

### ISSUE THREAD

**Issue by terutika0604** [mt8/base-item-list#15]
商品リストの表示順を最新のものより表示するように変更したいのですがどうしたらよいでしょうか。

**Comment by mt8** [comment]
この辺でPHPでソートするとかですね。
https://github.com/mt8/base-item-list/blob/master/class-BaseItemList.php#L74

**Comment by terutika0604** [comment]
APIを操作したことがなくそれぞれの変数が何を表しているかもわからない状態です。
お手数ですがもう少し詳しく解説していただけないでしょうか。
誠に申し訳ございません。

**Comment by mt8** [comment]
不具合報告ではないのでクローズします。
プログラムのサポートが必要な場合は別途お問い合わせください

**Comment by ShortArrow** [comment]
@mt8 以下のような説明をReadmeに追加してもよいですか？これで少し戸惑ったので、書いてあると助かる人はいると思います。

## 使用例
```
[BASE_ITEM  q="キーボード" count=32 name="keyboard" cache="60" sort="item_id asc"]
```

sortの値に`desc`または`asc`を指定し忘れると、何も表示されません。
例えば`[BASE_ITEM  q="キーボード" count=32 name="keyboard" cache="60" sort="item_id"]`などとすると、
何も表示されません。

**Comment by mt8** [comment]
@ShortArrow プルリクエストください。
