### ISSUE TITLE
消した商品が表示される

### ISSUE THREAD

**Issue by ShortArrow** [mt8/base-item-list#19]
# 現象

[BASE_ITEM]という単純なショートコードで、消したはずの商品が先頭に２個表示されます。

# 解決案

baseのDBをキレイにするリフレッシュボタン、プラグインのcacheをクリアするリフレッシュボタンなどを追加したら、ライトユーザーにも問題が解決しやすいでしょうか？

# バージョン

バージョン: 1.1.7
WPバージョン: 5.8

**Comment by ShortArrow** [comment]
[APIドキュメント](https://docs.thebase.in/docs/api/items/search)には、

> ※商品情報が全文検索用DBに反映されるまでに最大1時間ほどかかる場合があります。

との記載がありますが、当方では、全商品数が４０以下で２時間経過後も更新できていない状況です。

**Comment by ShortArrow** [comment]
３時間程度で更新完了しました。何だったのでしょう？

**Comment by mt8** [comment]
使ってるAPIは検索APIなのでドキュメントはこっちですね。
https://docs.thebase.in/docs/api/search/

何だったのでしょう？と言われても情報が無さすぎて分かりませんね。

**Comment by mt8** [comment]
> baseのDBをキレイにするリフレッシュボタン
>プラグインのcacheをクリアするリフレッシュボタンなどを追加したら、ライトユーザーにも問題が解決しやすいでしょうか？

APIのレスポンス結果はTransientにキャッシュさせているので、クリアボタン是非プルリクお待ちしてます

**Comment by ShortArrow** [comment]
> 使ってるAPIは検索APIなのでドキュメントはこっちですね。
> https://docs.thebase.in/docs/api/search/
> 
> 何だったのでしょう？と言われても情報が無さすぎて分かりませんね。

ありがとうございます！そちらでしたか

**Comment by mt8** [comment]
これいいですね！
https://github.com/ShortArrow/snow-monkey-child-with-base-item-list
