### ISSUE TITLE
商品をカテゴリーで絞り込んで取得したい

### ISSUE THREAD

**Issue by masakawai** [mt8/base-item-list#29]
商品をカテゴリーで絞り込んで取得したいです
BASE API のパラメーターに fields というのがあり、これを指定することで検索対象のカラムを指定できます
これを利用して、カテゴリーを指定して商品が取得できると思います
テストしてうまく行ったコードをプルリクエストしましたので、ご確認ください

**Comment by mt8** [comment]
@masakawai 時間が空いてしまい申し訳ないです！6.2テストと同時に取り込ませていただきました！
プルリクエストありがとうございました！
