### ISSUE TITLE
"error":"auth_error"が表示されてしまします。

### ISSUE THREAD

**Issue by bra-kodairakenya** [mt8/base-item-list#5]
この度は素晴らしいAPIとプラグインを提供してくださりありがとうございます。

WordPressのプラグインをhttp://mt8.biz/base-item-list/
こちらの記載通り進めたのですが、表示がされませんでした。調べたところ、class-BaseItemList.phpファイル内の

public function request_api( $args ) {
    $endpoint = 'https://api.thebase.in/1/search';
    $query = build_query( $args );
    $response = wp_remote_get( $endpoint . '?' . $query );
    if ( 200 !== wp_remote_retrieve_response_code( $response ) ) {
        return null;
    }
    return json_decode( wp_remote_retrieve_body( $response ) );
}

こちらでprint_r($response);をしたところ"error":"auth_error","error_description"といったエラーが見つかりました。
ご対応いただけますと幸いです。

※追記
client_id、client_secret、shop_idはちゃんと出力できておりました！

**Comment by mt8** [comment]
認証エラーのようですね。

念のため以下ご確認ください。
- BASE APIアプリ作成時に、「検索APIを利用する」にチェックを入れている
- (検索API用)の、client_id・client_secretを設定しているBASE API アプリ内に検索用ではない、client_id・client_secretも記載されているので注意が必要です

**Comment by bra-kodairakenya** [comment]
「検索APIを利用する」にチェックを入れている
こちらにチェックを入れ忘れていたのかもしれません。再度、アプリの承認申請を送らせていただきます！
迅速な対応ありがとうございます！

**Comment by mt8** [comment]
:+1:
