### ISSUE TITLE
デフォルトスタイルCSSを実装する

### ISSUE THREAD

**Issue by mt8** [mt8/base-item-list#9]
以下のファイルにCSS当てる
https://github.com/mt8/base-item-list/blob/master/base_items.php

**Comment by 466548** [comment]
Hello!
There is not test environment. However, I made it.

.base_items_list {
 display: inline-block;
 overflow: hidden;
 width: 100%;
 margin: 1em 0;
 padding: 0;
 text-decoration: none;
}

.base_item .base_item_title {
    font-size:  14px;
    font-size:  0.8em;
}

.base_item dd img{
 max-width: 100%;
}

**Comment by soratomo** [comment]
How are you
I have little experience with Git,
If there is anything I can do, I will write it.

**Comment by mt8** [comment]
1.1で対応
